### ISSUE TITLE
Fails to build on `aarch64_be-unknown-linux-gnu`

### ISSUE THREAD

**Issue by joshlf** [BurntSushi/memchr#174]
See [this GitHub Actions build failure](https://github.com/google/zerocopy/actions/runs/13525370851/job/37794443731?pr=2388), which builds memchr 2.7.4 with nightly-2025-02-24 for target `aarch64_be-unknown-linux-gnu`.

This may relate to https://github.com/rust-lang/stdarch/issues/1484, which was recently resolved.

<details>
<summary>Full error output</summary>

```text
error[E0432]: unresolved import `core::arch::aarch64::uint8x16_t`
  --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b5[57](https://github.com/google/zerocopy/actions/runs/13521505509/job/37781631983?pr=2387#step:7:58)f/memchr-2.7.4/src/arch/aarch64/neon/memchr.rs:23:5
   |
23 | use core::arch::aarch64::uint8x16_t;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `uint8x16_t` in `core_arch::arch::aarch64`

error[E0432]: unresolved import `core::arch::aarch64::uint8x16_t`
  --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/arch/aarch64/neon/packedpair.rs:11:5
   |
11 | use core::arch::aarch64::uint8x16_t;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `uint8x16_t` in `core_arch::arch::aarch[64](https://github.com/google/zerocopy/actions/runs/13521505509/job/37781631983?pr=2387#step:7:65)`

error[E0412]: cannot find type `uint8x16_t` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:298:21
    |
298 |     impl Vector for uint8x16_t {
    |                     ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `uint8x16_t` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:305:38
    |
305 |         unsafe fn splat(byte: u8) -> uint8x16_t {
    |                                      ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `uint8x16_t` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:310:52
    |
310 |         unsafe fn load_aligned(data: *const u8) -> uint8x16_t {
    |                                                    ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `uint8x16_t` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:317:54
    |
317 |         unsafe fn load_unaligned(data: *const u8) -> uint8x16_t {
    |                                                      ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `uint8x16_t` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1[94](https://github.com/google/zerocopy/actions/runs/13521505509/job/37781631983?pr=2387#step:7:95)9cf8c6b5b557f/memchr-2.7.4/src/vector.rs:331:49
    |
331 |         unsafe fn cmpeq(self, vector2: Self) -> uint8x16_t {
    |                                                 ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `uint8x16_t` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:336:47
    |
336 |         unsafe fn and(self, vector2: Self) -> uint8x16_t {
    |                                               ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `uint8x16_t` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:341:46
    |
341 |         unsafe fn or(self, vector2: Self) -> uint8x16_t {
    |                                              ^^^^^^^^^^ not found in this scope

   Compiling rustc-demangle v0.1.24
error[E0425]: cannot find function `vdupq_n_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:306:13
    |
306 |             vdupq_n_u8(byte)
    |             ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `vld1q_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:318:13
    |
318 |             vld1q_u8(data)
    |             ^^^^^^^^ not found in this scope

error[E0425]: cannot find function `vreinterpretq_u16_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:323:26
    |
323 |             let asu16s = vreinterpretq_u16_u8(self);
    |                          ^^^^^^^^^^^^^^^^^^^^------
    |                          |
    |                          help: try calling `vreinterpretq_u16_u8` as a method: `self.vreinterpretq_u16_u8()`

error[E0425]: cannot find function `vshrn_n_u16` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:324:24
    |
324 |             let mask = vshrn_n_u16(asu16s, 4);
    |                        ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `vreinterpret_u64_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:325:25
    |
325 |             let asu64 = vreinterpret_u64_u8(mask);
    |                         ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `vget_lane_u64` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:326:28
    |
326 |             let scalar64 = vget_lane_u64(asu64, 0);
    |                            ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `vceqq_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:332:13
    |
332 |             vceqq_u8(self, vector2)
    |             ^^^^^^^^---------------
    |             |
    |             help: try calling `vceqq_u8` as a method: `self.vceqq_u8(vector2)`

error[E0425]: cannot find function `vandq_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:337:13
    |
337 |             vandq_u8(self, vector2)
    |             ^^^^^^^^---------------
    |             |
    |             help: try calling `vandq_u8` as a method: `self.vandq_u8(vector2)`

error[E0425]: cannot find function `vorrq_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:342:13
    |
342 |             vorrq_u8(self, vector2)
    |             ^^^^^^^^---------------
    |             |
    |             help: try calling `vorrq_u8` as a method: `self.vorrq_u8(vector2)`

error[E0425]: cannot find function `vpmaxq_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-[194](https://github.com/google/zerocopy/actions/runs/13521505509/job/37781631983?pr=2387#step:7:195)9cf8c6b5b557f/memchr-2.7.4/src/vector.rs:353:44
    |
353 |             let low = vreinterpretq_u64_u8(vpmaxq_u8(self, self));
    |                                            ^^^^^^^^^------------
    |                                            |
    |                                            help: try calling `vpmaxq_u8` as a method: `self.vpmaxq_u8(self)`

error[E0425]: cannot find function `vreinterpretq_u64_u8` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:353:23
    |
353 |             let low = vreinterpretq_u64_u8(vpmaxq_u8(self, self));
    |                       ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `vgetq_lane_u64` in this scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memchr-2.7.4/src/vector.rs:354:13
    |
354 |             vgetq_lane_u64(low, 0) != 0
    |             ^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0412, E0425, E0432.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `memchr` (lib) due to 21 previous errors
```

</details>

**Comment by BurntSushi** [comment]
[This PR](https://github.com/BurntSushi/memchr/pull/162) was submitted to fix this I think, but did it by just disabling all NEON paths on big endian. Is that the right fix for this? @workingjubilee [commented that it should be fixed upstream](https://github.com/BurntSushi/memchr/pull/162#issuecomment-2395591319). And it looks like [this PR was just merged upstream to fix the problem](https://github.com/rust-lang/stdarch/pull/1708).

So I guess I'm unclear as to the action item here for memchr. It seems wholly like a problem upstream and not something to be fixed in `memchr`. To be clear, I'm also more than willing to be practical about this if we know upstream isn't going to be fixed any time soon (in which case, something like #162 seems fine), but it seems like that's not the case?

Can you say more about what specific action you're looking for here?

**Comment by BurntSushi** [comment]
I guess the first thing to check here is whether https://github.com/rust-lang/stdarch/pull/1708 is actually in the latest nightly.

**Comment by joshlf** [comment]
> I guess the first thing to check here is whether [rust-lang/stdarch#1708](https://github.com/rust-lang/stdarch/pull/1708) is actually in the latest nightly.

Good point; I [tried again here](https://github.com/google/zerocopy/actions/runs/13528470460/job/37804819878?pr=2388) with 2025-02-25, which I assume is more likely to contain https://github.com/rust-lang/stdarch/pull/1708, and the issue still shows up. I know there are ways to check which commits are included in nightly, but I'm not sure what those ways are. Maybe somebody else can chime in.

**Comment by joshlf** [comment]
> Can you say more about what specific action you're looking for here?

I was under the impression that https://github.com/rust-lang/stdarch/pull/1708 ought to fix this, and so I figured that there might be some work memchr might need to do in order to be compatible with that fix. I'm not sure, though - that's just a guess as to the path forward.

The proximate issue for us is just being able to compile memchr (and thus compile our CI tests) on aarch64_be; since memchr is just an indirect dependency for us, we don't have any opinions about the best resolution - any resolution that gets memchr compiling is equally good from our perspective.

**Comment by joshlf** [comment]
Looks like it's [still failing](https://github.com/google/zerocopy/actions/runs/13566660752/job/37921196164?pr=2399) on nightly-2025-02-26.

**Comment by taiki-e** [comment]
> I guess the first thing to check here is whether [rust-lang/stdarch#1708](https://github.com/rust-lang/stdarch/pull/1708) is actually in the latest nightly.

https://github.com/rust-lang/rust/pull/136831 (not yet merged) is a PR to include that change to std/core.

**Comment by Jamesbarford** [comment]
I'm of the disposition to believe this should now work; locally I can build the compiler with `./x.py build --stage 1 --target aarch64_be-unknown-linux-gnu`. As part of that `memchr` gets compiled successfully.

**Comment by joshlf** [comment]
Okay, confirmed that (save for unrelated wasm issues), we're able to roll our nightly toolchain and all of the tests build and pass on `aarch64_be-unknown-linux-gnu`.
